import { getApps, initializeApp } from "firebase-admin/app";
import { getFirestore, Timestamp } from "firebase-admin/firestore";

const PROJECT_ID = "demo-kabinet-25";
const AUTH_EMULATOR_URL = "http://127.0.0.1:9099";

interface TestAccount {
  username: string;
  password: string;
  role: "teacher" | "student";
  theme: "light" | "dark";
}

const accounts: TestAccount[] = [
  {
    username: "test.teacher",
    password: "Teacher-test-2026!",
    role: "teacher",
    theme: "light",
  },
  {
    username: "test.student",
    password: "Student-test-2026!",
    role: "student",
    theme: "dark",
  },
];

const achievementDefinitions = [
  ["first-step", "Первый шаг", "Отправить первое домашнее задание", "spark"],
  ["battle-baptism", "Боевое крещение", "Пройти первый пробник", "shield"],
  ["on-time", "Точно в срок", "Сдать работу вовремя", "clock"],
  ["momentum", "Взял темп", "Серия из трёх работ", "flame"],
  ["iron-streak", "Железная серия", "Серия из семи работ", "flame"],
  ["unstoppable", "Не остановить", "Серия из четырнадцати работ", "rocket"],
  ["sniper", "Снайпер", "Устойчиво решать задание на 90%", "target"],
  ["growth", "Вот это рост", "Прибавить 10 п.п. на пробнике", "trend"],
  ["comeback", "Камбэк", "Успешно исправить работу", "return"],
  ["personal-best", "Личный рекорд", "Обновить лучший результат", "trophy"],
  ["first-mastery", "Первое освоение", "Освоить первое задание", "star"],
  ["halfway", "Полпути", "Достичь готовности 50%", "route"],
  ["almost-ready", "Почти готов", "Достичь готовности 75%", "badge"],
  ["exam-ready", "Готов к экзамену", "Достичь готовности 90%", "crown"],
] as const;

async function createAuthAccount(account: TestAccount): Promise<string> {
  const response = await fetch(
    `${AUTH_EMULATOR_URL}/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-api-key`,
    {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        email: `${account.username}@kabinet25.example.com`,
        password: account.password,
        returnSecureToken: true,
      }),
    },
  );

  if (!response.ok) {
    throw new Error(`Auth Emulator fixture failed: ${await response.text()}`);
  }

  const result = (await response.json()) as { localId?: string };
  if (!result.localId) {
    throw new Error("Auth Emulator did not return a uid");
  }
  return result.localId;
}

export default async function globalSetup() {
  if (!process.env.FIRESTORE_EMULATOR_HOST) {
    throw new Error(
      "Phase 1 E2E tests must run inside Firebase emulators:exec",
    );
  }

  const app =
    getApps()[0] ??
    initializeApp({ projectId: PROJECT_ID }, "phase-1-e2e-fixtures");
  const db = getFirestore(app);
  const teacherUid = await createAuthAccount(accounts[0]);
  const studentUid = await createAuthAccount(accounts[1]);
  const now = Timestamp.fromDate(new Date("2026-08-14T00:00:00.000Z"));
  const freshMaterialCreatedAt = Timestamp.fromMillis(Date.now() - 86_400_000);
  const localNow = new Date();
  const localToday = `${localNow.getFullYear()}-${String(localNow.getMonth() + 1).padStart(2, "0")}-${String(localNow.getDate()).padStart(2, "0")}`;
  const literacyCriteria = [
    {
      code: "ГК1",
      title: "Орфография",
      max: 3,
      errorLabel: "Орфографических ошибок",
    },
    {
      code: "ГК2",
      title: "Пунктуация",
      max: 3,
      errorLabel: "Пунктуационных ошибок",
    },
    {
      code: "ГК3",
      title: "Грамматика",
      max: 3,
      errorLabel: "Грамматических ошибок",
    },
    { code: "ГК4", title: "Речь", max: 3, errorLabel: "Речевых ошибок" },
  ];
  const factualCriterion = {
    code: "ФК",
    max: 1,
    errorLabel: "Фактических ошибок",
  };
  const essayReviewCriteria = {
    content: [
      { code: "СК1", title: "Смысловой анализ", max: 1 },
      { code: "СК2", title: "Примеры из текста", max: 3 },
      { code: "СК3", title: "Логика", max: 2 },
      { code: "СК4", title: "Композиция", max: 1 },
    ],
    literacy: literacyCriteria,
    factual: factualCriterion,
  };
  const expositionReviewCriteria = {
    content: [
      { code: "ИК1", title: "Содержание", max: 2 },
      { code: "ИК2", title: "Сжатие", max: 2 },
      { code: "ИК3", title: "Связность", max: 2 },
    ],
    literacy: literacyCriteria,
    factual: factualCriterion,
  };
  const phase5AssignedAt = Timestamp.fromDate(
    new Date("2026-08-13T00:00:00.000Z"),
  );
  const tomorrowAtTen = new Date();
  tomorrowAtTen.setDate(tomorrowAtTen.getDate() + 1);
  tomorrowAtTen.setHours(10, 0, 0, 0);
  const nextLessonStart = Timestamp.fromDate(tomorrowAtTen);
  const nextLessonEnd = Timestamp.fromMillis(tomorrowAtTen.getTime() + 3_600_000);
  const dashboardLessonDate = new Date();
  dashboardLessonDate.setHours(12, 0, 0, 0);
  const dashboardOriginalDate = new Date();
  dashboardOriginalDate.setHours(16, 0, 0, 0);
  const dashboardLessonStart = Timestamp.fromDate(dashboardLessonDate);
  const dashboardLessonEnd = Timestamp.fromMillis(dashboardLessonDate.getTime() + 3_600_000);
  const originalLessonStart = Timestamp.fromDate(dashboardOriginalDate);
  const originalLessonEnd = Timestamp.fromMillis(dashboardOriginalDate.getTime() + 3_600_000);
  const homeworkDue = Timestamp.fromMillis(
    Date.now() + 4 * 24 * 60 * 60 * 1000,
  );
  const phase5HomeworkDue = Timestamp.fromMillis(
    Date.now() + 2 * 24 * 60 * 60 * 1000,
  );
  const mockTakenAt = Timestamp.fromMillis(
    Date.now() - 7 * 24 * 60 * 60 * 1000,
  );

  await Promise.all([
    ...achievementDefinitions.map(([code, title, description, iconKey]) =>
      db.doc(`achievementDefinitions/${code}`).set({
        code,
        title,
        description,
        iconKey,
        xpReward: 0,
        active: true,
        conditionConfig: {},
        schemaVersion: 1,
      }),
    ),
    db.doc(`users/${teacherUid}`).set({
      role: "teacher",
      displayName: "Кристина",
      username: accounts[0].username,
      usernameNormalized: accounts[0].username,
      teacherId: null,
      studentId: null,
      preferences: { theme: accounts[0].theme },
      timezone: { iana: "Asia/Novosibirsk", moscowOffsetMinutes: 240 },
      avatarKey: "animal_05",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc(`users/${studentUid}`).set({
      role: "student",
      username: accounts[1].username,
      usernameNormalized: accounts[1].username,
      teacherId: teacherUid,
      studentId: studentUid,
      preferences: { theme: accounts[1].theme },
      timezone: { iana: "Europe/Moscow", moscowOffsetMinutes: 180 },
      avatarKey: "student_03",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc(`students/${studentUid}`).set({
      teacherId: teacherUid,
      displayName: "Тестовая ученица",
      classGrade: 9,
      status: "active",
      defaultConference: {
        provider: "zoom",
        joinUrl: "https://example.com/local-classroom",
        meetingId: null,
        passcode: null,
        chatUrl: null,
      },
      conferenceLinks: [
        {
          id: "primary",
          label: "Основная",
          provider: "zoom",
          joinUrl: "https://example.com/local-classroom",
          isDefault: true,
        },
      ],
      avatarKey: "student_03",
      createdAt: now,
      updatedAt: now,
      archivedAt: null,
      schemaVersion: 1,
    }),
    db.doc("examBlueprints/test-oge-russian-2027").set({
      programType: "oge",
      subject: "russian",
      year: 2027,
      version: "test-v1",
      status: "active",
      maxScore: 37,
      gradeThresholds: { 2: 0, 3: 15, 4: 24, 5: 31 },
      gradeRules: [
        { grade: 2, minScore: 0, maxScore: 14 },
        { grade: 3, minScore: 15, maxScore: 25 },
        {
          grade: 4,
          minScore: 26,
          maxScore: 32,
          minGkScore: 6,
          fallbackGrade: 3,
        },
        {
          grade: 5,
          minScore: 33,
          maxScore: 37,
          minGkScore: 9,
          fallbackGrade: 4,
        },
      ],
      sections: [
        { code: "test", title: "Тест", maxScore: 11 },
        { code: "exposition", title: "Изложение", maxScore: 6 },
        { code: "essay", title: "Сочинение", maxScore: 7 },
        { code: "literacy", title: "Грамотность", maxScore: 12 },
        { code: "factual", title: "ФК", maxScore: 1 },
      ],
      tasks: [
        {
          number: 1,
          title: "Изложение",
          maxScore: 6,
          sectionCode: "exposition",
        },
        ...Array.from({ length: 11 }, (_, index) => ({
          number: index + 2,
          title: `Задание №${index + 2}`,
          maxScore: 1,
          sectionCode: "test",
        })),
        { number: 13, title: "Сочинение", maxScore: 7, sectionCode: "essay" },
      ],
      writingCriteria: {
        essay: [
          { code: "СК1", title: "Смысловой анализ", max: 1 },
          { code: "СК2", title: "Примеры из текста", max: 3 },
          { code: "СК3", title: "Логика", max: 2 },
          { code: "СК4", title: "Композиция", max: 1 },
        ],
        exposition: [
          { code: "ИК1", title: "Содержание", max: 2 },
          { code: "ИК2", title: "Сжатие", max: 2 },
          { code: "ИК3", title: "Связность", max: 2 },
        ],
        literacy: [
          {
            code: "ГК1",
            title: "Орфография",
            max: 3,
            errorLabel: "Орфографических ошибок",
          },
          {
            code: "ГК2",
            title: "Пунктуация",
            max: 3,
            errorLabel: "Пунктуационных ошибок",
          },
          {
            code: "ГК3",
            title: "Грамматика",
            max: 3,
            errorLabel: "Грамматических ошибок",
          },
          { code: "ГК4", title: "Речь", max: 3, errorLabel: "Речевых ошибок" },
        ],
        factual: { code: "ФК", max: 1, errorLabel: "Фактических ошибок" },
      },
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("programProfiles/test-oge-program").set({
      type: "oge",
      subject: "russian",
      targetYear: 2027,
      title: "ОГЭ · Русский язык · 2027",
      examDate: Timestamp.fromDate(new Date("2027-06-01T00:00:00.000Z")),
      status: "active",
      examBlueprintId: "test-oge-russian-2027",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("studentPrograms/test-student-program-1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      programProfileId: "test-oge-program",
      status: "active",
      goal: {
        type: "grade",
        targetGrade: 4,
        targetScore: null,
        displayText: "ОГЭ на 4",
      },
      startedAt: now,
      completedAt: null,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("lessonSeries/test-series-1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      frequency: "weekly",
      weekdays: [4],
      interval: 1,
      startLocalTime: "10:00",
      durationMinutes: 60,
      baseTimezone: "Europe/Moscow",
      active: true,
      visibility: "program",
      selectedStudentIds: [],
      allowedStudentIds: [studentUid],
      startsOn: "2026-08-13",
      endsOn: null,
      cancelledAt: null,
      cancelledBy: null,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("lessons/test-lesson-1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      lessonSeriesId: "test-series-1",
      startAt: nextLessonStart,
      endAt: nextLessonEnd,
      originalStartAt: null,
      rescheduledFromLessonId: null,
      rescheduledToLessonId: null,
      status: "planned",
      topic: "Тестовое занятие по пунктуации",
      lessonSummary: {
        homeworkResultText: null,
        teacherComment: null,
        focusNotes: [],
      },
      examTaskNumbers: [],
      homeworkResolution: "pending",
      conferenceUrl: null,
      billingType: "regular",
      billingIdentityId: "test-lesson-1",
      paymentStatus: "unpaid",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("lessons/dashboard-rescheduled-current").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      lessonSeriesId: null,
      startAt: dashboardLessonStart,
      endAt: dashboardLessonEnd,
      originalStartAt: originalLessonStart,
      rescheduledFromLessonId: "dashboard-rescheduled-original",
      rescheduledToLessonId: null,
      wasRescheduled: true,
      status: "planned",
      topic: "Пунктуационный практикум",
      lessonSummary: {
        homeworkResultText: null,
        teacherComment: null,
        focusNotes: [],
      },
      examTaskNumbers: [],
      homeworkResolution: "pending",
      conferenceUrl: null,
      billingType: "regular",
      billingIdentityId: "dashboard-rescheduled-billing",
      paymentStatus: "unpaid",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("lessons/dashboard-rescheduled-original").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      lessonSeriesId: null,
      startAt: originalLessonStart,
      endAt: originalLessonEnd,
      originalStartAt: null,
      rescheduledFromLessonId: null,
      rescheduledToLessonId: "dashboard-rescheduled-current",
      status: "rescheduled",
      topic: null,
      lessonSummary: {
        homeworkResultText: null,
        teacherComment: null,
        focusNotes: [],
      },
      examTaskNumbers: [],
      homeworkResolution: "pending",
      conferenceUrl: null,
      billingType: "regular",
      billingIdentityId: "dashboard-rescheduled-billing",
      paymentStatus: "unpaid",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworks/test-homework-1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      sourceLessonId: null,
      type: "written",
      title: "Тестовое исходное ДЗ",
      description: "Повторить пунктуацию.",
      examTaskNumbers: [],
      assignedAt: now,
      dueAt: homeworkDue,
      status: "assigned",
      requiredAmount: null,
      items: [
        {
          itemId: "test-written-item",
          type: "essay",
          title: "Написать сочинение",
          description: null,
          requiredAmount: null,
          examTaskNumbers: [13],
          attachments: [],
          materialIds: [],
          sortOrder: 0,
        },
      ],
      attachments: [],
      reviewCriteria: {
        content: [
          { code: "СК1", title: "Смысловой анализ", max: 1 },
          { code: "СК2", title: "Примеры из текста", max: 3 },
          { code: "СК3", title: "Логика", max: 2 },
          { code: "СК4", title: "Композиция", max: 1 },
        ],
        literacy: [],
        factual: null,
      },
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworks/phase5-homework").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      sourceLessonId: null,
      type: "practice",
      title: "Практика: задания №2–5",
      description: "Выполнить четыре задания и указать свой результат.",
      examTaskNumbers: [2, 3, 4, 5],
      assignedAt: phase5AssignedAt,
      dueAt: phase5HomeworkDue,
      dueDate: null,
      dueTime: null,
      dueTimezone: "Europe/Moscow",
      status: "assigned",
      requiredAmount: 4,
      items: [
        {
          itemId: "phase5-item-1",
          type: "practice",
          title: "Решить задания №2–5",
          description: null,
          requiredAmount: 4,
          examTaskNumbers: [2, 3, 4, 5],
          attachments: [],
          materialIds: ["test-material-practice"],
          sortOrder: 0,
        },
      ],
      attachments: [],
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworks/reviewed-homework").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      sourceLessonId: "test-completed-lesson",
      type: "essay",
      title: "Сочинение по прочитанному тексту",
      description: "Проверенная работа для приёмки.",
      examTaskNumbers: [13],
      assignedAt: Timestamp.fromMillis(Date.now() - 6 * 86_400_000),
      dueAt: Timestamp.fromMillis(Date.now() - 4 * 86_400_000),
      status: "checked",
      requiredAmount: null,
      items: [
        {
          itemId: "reviewed-essay",
          type: "essay",
          title: "Написать сочинение",
          description: null,
          requiredAmount: null,
          examTaskNumbers: [13],
          attachments: [],
          materialIds: [],
          sortOrder: 0,
        },
      ],
      attachments: [],
      reviewCriteria: {
        content: [
          { code: "СК1", title: "Смысловой анализ", max: 1 },
          { code: "СК2", title: "Примеры", max: 3 },
          { code: "СК3", title: "Логика", max: 2 },
          { code: "СК4", title: "Композиция", max: 1 },
        ],
        literacy: [],
        factual: null,
      },
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworkSubmissions/reviewed-homework__submission__1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      homeworkId: "reviewed-homework",
      submissionNumber: 1,
      studentInput: {
        completed: true,
        selfReportedEarned: null,
        selfReportedMax: null,
        note: "Готово",
        externalAttachmentUrls: [],
        attachments: [
          {
            id: "student-essay-photo",
            kind: "external",
            title: "Сочинение ученицы.jpg",
            storagePath: null,
            url: "https://placehold.co/900x1200/png?text=Student+Essay",
            contentType: "image/png",
          },
        ],
        itemProgress: [
          {
            itemId: "reviewed-essay",
            completed: true,
            selfReportedEarned: null,
            selfReportedMax: null,
            responseText: null,
            attachments: [],
          },
        ],
      },
      teacherEvaluation: {
        scoreEarned: 5,
        scoreMax: 7,
        criteria: [
          { code: "СК1", earned: 1, max: 1, errorsCount: null },
          { code: "СК2", earned: 2, max: 3, errorsCount: null },
          { code: "СК3", earned: 1, max: 2, errorsCount: null },
          { code: "СК4", earned: 1, max: 1, errorsCount: null },
        ],
        issues: [],
        comment: "Структура стала лучше. Доработай второй пример.",
        checkedAt: now,
      },
      status: "checked",
      submittedAt: Timestamp.fromMillis(Date.now() - 4 * 86_400_000),
      reviewedUnread: true,
      reviewedOpenedAt: null,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworks/submitted-essay-homework").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      sourceLessonId: null,
      type: "essay",
      title: "Сочинение · проверка по критериям",
      description: "Работа ожидает структурированной проверки.",
      examTaskNumbers: [13],
      assignedAt: now,
      dueAt: homeworkDue,
      status: "submitted",
      requiredAmount: null,
      items: [
        {
          itemId: "submitted-essay-item",
          type: "essay",
          reviewCriteria: essayReviewCriteria,
          title: "Написать сочинение",
          description: null,
          requiredAmount: null,
          examTaskNumbers: [13],
          attachments: [],
          materialIds: [],
          sortOrder: 0,
        },
      ],
      attachments: [],
      reviewCriteria: {
        content: [
          { code: "СК1", title: "Смысловой анализ", max: 1 },
          { code: "СК2", title: "Примеры", max: 3 },
          { code: "СК3", title: "Логика", max: 2 },
          { code: "СК4", title: "Композиция", max: 1 },
        ],
        literacy: [
          {
            code: "ГК1",
            title: "Орфография",
            max: 3,
            errorLabel: "Орфографических ошибок",
          },
          {
            code: "ГК2",
            title: "Пунктуация",
            max: 3,
            errorLabel: "Пунктуационных ошибок",
          },
        ],
        factual: { code: "ФК", max: 1, errorLabel: "Фактических ошибок" },
      },
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworkSubmissions/submitted-essay-homework__submission__1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      homeworkId: "submitted-essay-homework",
      submissionNumber: 1,
      studentInput: {
        completed: true,
        selfReportedEarned: null,
        selfReportedMax: null,
        note: "Проверьте второй аргумент.",
        externalAttachmentUrls: [],
        attachments: [
          {
            id: "student-essay-review-photo",
            kind: "external",
            title: "Работа на проверку.jpg",
            storagePath: null,
            url: "https://placehold.co/900x1200/png?text=Essay+Review",
            contentType: "image/png",
          },
        ],
        itemProgress: [
          {
            itemId: "submitted-essay-item",
            completed: true,
            selfReportedEarned: null,
            selfReportedMax: null,
            responseText: null,
            attachments: [],
          },
        ],
      },
      teacherEvaluation: null,
      status: "submitted",
      submittedAt: now,
      reviewedUnread: false,
      reviewedOpenedAt: null,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworks/submitted-exposition-homework").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      sourceLessonId: null,
      type: "exposition",
      title: "Изложение · проверка по критериям",
      description: "Изложение ожидает проверки.",
      examTaskNumbers: [1],
      assignedAt: now,
      dueAt: homeworkDue,
      status: "submitted",
      requiredAmount: null,
      items: [
        {
          itemId: "submitted-exposition-item",
          type: "exposition",
          reviewCriteria: expositionReviewCriteria,
          title: "Написать изложение",
          description: null,
          requiredAmount: null,
          examTaskNumbers: [1],
          attachments: [],
          materialIds: [],
          sortOrder: 0,
        },
      ],
      attachments: [],
      reviewCriteria: {
        content: [
          { code: "ИК1", title: "Содержание", max: 2 },
          { code: "ИК2", title: "Сжатие", max: 2 },
          { code: "ИК3", title: "Связность", max: 2 },
        ],
        literacy: [
          {
            code: "ГК1",
            title: "Орфография",
            max: 3,
            errorLabel: "Орфографических ошибок",
          },
          {
            code: "ГК2",
            title: "Пунктуация",
            max: 3,
            errorLabel: "Пунктуационных ошибок",
          },
        ],
        factual: null,
      },
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db
      .doc("homeworkSubmissions/submitted-exposition-homework__submission__1")
      .set({
        teacherId: teacherUid,
        studentId: studentUid,
        homeworkId: "submitted-exposition-homework",
        submissionNumber: 1,
        studentInput: {
          completed: true,
          selfReportedEarned: null,
          selfReportedMax: null,
          note: "Изложение готово.",
          externalAttachmentUrls: [],
          attachments: [],
          itemProgress: [
            {
              itemId: "submitted-exposition-item",
              completed: true,
              selfReportedEarned: null,
              selfReportedMax: null,
              responseText: null,
              attachments: [],
            },
          ],
        },
        teacherEvaluation: null,
        status: "submitted",
        submittedAt: now,
        reviewedUnread: false,
        reviewedOpenedAt: null,
        createdAt: now,
        updatedAt: now,
        schemaVersion: 1,
      }),
    db.doc("homeworks/multi-structured-homework").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      sourceLessonId: null,
      type: "written",
      title: "Сочинение и изложение · отдельная проверка",
      description: "Два письменных пункта в одном пакете.",
      examTaskNumbers: [1, 13],
      assignedAt: Timestamp.fromMillis(now.toMillis() - 10 * 86_400_000),
      dueAt: homeworkDue,
      status: "submitted",
      requiredAmount: null,
      items: [
        {
          itemId: "multi-essay",
          type: "essay",
          title: "Сочинение №13",
          description: null,
          requiredAmount: null,
          examTaskNumbers: [13],
          attachments: [],
          materialIds: [],
          sortOrder: 0,
          reviewCriteria: essayReviewCriteria,
        },
        {
          itemId: "multi-exposition",
          type: "exposition",
          title: "Изложение №1",
          description: null,
          requiredAmount: null,
          examTaskNumbers: [1],
          attachments: [],
          materialIds: [],
          sortOrder: 1,
          reviewCriteria: expositionReviewCriteria,
        },
      ],
      attachments: [],
      reviewCriteria: essayReviewCriteria,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("homeworkSubmissions/multi-structured-homework__submission__1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      homeworkId: "multi-structured-homework",
      submissionNumber: 1,
      studentInput: {
        completed: true,
        selfReportedEarned: null,
        selfReportedMax: null,
        note: "Обе работы готовы.",
        externalAttachmentUrls: [],
        attachments: [],
        itemProgress: [
          {
            itemId: "multi-essay",
            completed: true,
            selfReportedEarned: null,
            selfReportedMax: null,
            responseText: null,
            attachments: [],
          },
          {
            itemId: "multi-exposition",
            completed: true,
            selfReportedEarned: null,
            selfReportedMax: null,
            responseText: null,
            attachments: [],
          },
        ],
      },
      teacherEvaluation: null,
      status: "submitted",
      submittedAt: now,
      reviewedUnread: false,
      reviewedOpenedAt: null,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("materials/test-material-punctuation").set({
      teacherId: teacherUid,
      programProfileIds: ["test-oge-program"],
      examTaskNumbers: [3, 5],
      title: "Пунктуация в сложном предложении",
      type: "link",
      storagePath: null,
      externalUrl: "https://example.com/punctuation",
      tags: ["полезное", "пунктуация"],
      active: true,
      visibility: "program",
      selectedStudentIds: [],
      allowedStudentIds: [studentUid],
      folderId: "test-folder-russian",
      favorite: true,
      lastUsedAt: now,
      createdAt: freshMaterialCreatedAt,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("materials/test-material-practice").set({
      teacherId: teacherUid,
      programProfileIds: ["test-oge-program"],
      examTaskNumbers: [3],
      title: "Тренажёр задания №3",
      type: "interactive",
      storagePath: null,
      externalUrl: "https://example.com/practice-3",
      tags: ["тренировка"],
      active: true,
      visibility: "program",
      selectedStudentIds: [],
      allowedStudentIds: [studentUid],
      folderId: "test-folder-russian",
      favorite: false,
      lastUsedAt: null,
      createdAt: freshMaterialCreatedAt,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("materials/test-material-other-program").set({
      teacherId: teacherUid,
      programProfileIds: ["another-program"],
      examTaskNumbers: [],
      title: "Материал другой программы",
      type: "video",
      storagePath: null,
      externalUrl: "https://example.com/other",
      tags: ["полезное"],
      active: true,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("mockExams/test-mock-1").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      examBlueprintId: "test-oge-russian-2027",
      title: "Тестовый исходный пробник",
      takenAt: mockTakenAt,
      takenDate: mockTakenAt.toDate().toISOString().slice(0, 10),
      taskResults: [
        { taskNumber: 2, earned: 0, max: 1 },
        { taskNumber: 3, earned: 0, max: 1 },
        { taskNumber: 4, earned: 1, max: 1 },
        { taskNumber: 5, earned: 1, max: 1 },
        { taskNumber: 6, earned: 0, max: 1 },
        { taskNumber: 7, earned: 1, max: 1 },
        { taskNumber: 8, earned: 1, max: 1 },
        { taskNumber: 9, earned: 1, max: 1 },
        { taskNumber: 10, earned: 0, max: 1 },
        { taskNumber: 11, earned: 1, max: 1 },
        { taskNumber: 12, earned: 1, max: 1 },
      ],
      sections: {
        test: { earned: 7, max: 11 },
        exposition: {
          earned: 6,
          max: 6,
          criteria: [
            { code: "ИК1", earned: 2, max: 2, errorsCount: null },
            { code: "ИК2", earned: 2, max: 2, errorsCount: null },
            { code: "ИК3", earned: 2, max: 2, errorsCount: null },
          ],
        },
        essay: {
          earned: 5,
          max: 7,
          criteria: [
            { code: "СК1", earned: 1, max: 1, errorsCount: null },
            { code: "СК2", earned: 1, max: 3, errorsCount: null },
            { code: "СК3", earned: 2, max: 2, errorsCount: null },
            { code: "СК4", earned: 1, max: 1, errorsCount: null },
          ],
          comment: "Второй пример из текста не засчитан.",
        },
        literacy: {
          earned: 2,
          max: 12,
          criteria: [
            {
              code: "ГК1",
              earned: 0,
              max: 3,
              errorsCount: 6,
              category: "orthography",
            },
            {
              code: "ГК2",
              earned: 0,
              max: 3,
              errorsCount: 8,
              category: "punctuation",
            },
            {
              code: "ГК3",
              earned: 2,
              max: 3,
              errorsCount: 2,
              category: "grammar",
            },
            {
              code: "ГК4",
              earned: 0,
              max: 3,
              errorsCount: 6,
              category: "speech",
            },
          ],
        },
        factualAccuracy: { earned: 0, max: 1, errorsCount: 1 },
      },
      total: { earned: 20, max: 37 },
      grade: 3,
      teacherComment: "Второй пример из текста не засчитан.",
      taskObservations: [{ taskNumber: 6, observation: "Путает ПРЕ-/ПРИ-." }],
      publicRecommendations: [
        "Повторить приставки ПРЕ-/ПРИ-.",
        "Разобрать логику второго примера.",
      ],
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("mockExams/test-mock-previous").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      examBlueprintId: "test-oge-russian-2027",
      title: "Первый диагностический пробник",
      takenAt: Timestamp.fromMillis(Date.now() - 35 * 86_400_000),
      taskResults: Array.from({ length: 11 }, (_, index) => ({
        taskNumber: index + 2,
        earned: [2, 4, 5, 7, 8, 9].includes(index + 2) ? 1 : 0,
        max: 1,
      })),
      sections: {
        test: { earned: 6, max: 11 },
        exposition: { earned: 5, max: 6, criteria: [] },
        essay: { earned: 3, max: 7, criteria: [], comment: null },
        literacy: { earned: 2, max: 12, criteria: [] },
        factualAccuracy: { earned: 0, max: 1, errorsCount: 1 },
      },
      total: { earned: 16, max: 37 },
      grade: 3,
      teacherComment: "Стартовая диагностика.",
      taskObservations: [],
      publicRecommendations: ["Продолжить работу над сочинением."],
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("materialFolders/test-folder-russian").set({
      teacherId: teacherUid,
      title: "Русский язык · практика",
      active: true,
      allowedStudentIds: [studentUid],
      autoShareNewMaterials: false,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("lessons/test-completed-lesson").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      lessonSeriesId: "test-series-1",
      startAt: Timestamp.fromMillis(Date.now() - 3 * 86_400_000),
      endAt: Timestamp.fromMillis(Date.now() - 3 * 86_400_000 + 3_600_000),
      originalStartAt: null,
      rescheduledFromLessonId: null,
      rescheduledToLessonId: null,
      status: "completed",
      topic: "Сложное предложение и сочинение",
      lessonSummary: {
        homeworkResultText: "Проверено",
        teacherComment: "Хороший прогресс.",
        studentComment: "Закрепи постановку запятых.",
        focusNotes: ["Запятая между частями сложного предложения"],
        errors: ["Запятая между частями сложного предложения"],
      },
      examTaskNumbers: [3, 13],
      homeworkResolution: "assigned",
      conferenceUrl: null,
      billingType: "regular",
      billingIdentityId: "test-completed-lesson",
      understanding: { score: 7, status: "in_progress" },
      paymentStatus: "unpaid",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("lessonTeacherNotes/test-completed-lesson").set({
      teacherId: teacherUid,
      studentId: studentUid,
      lessonId: "test-completed-lesson",
      note: "Приватно: вернуться к микровыводу на следующем занятии.",
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("studentTaskCoverage/test-student-program-1__task__3").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      taskNumber: 3,
      state: "studied",
      sourceLessonIds: ["test-completed-lesson"],
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("studentTaskCoverage/test-student-program-1__task__13").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      taskNumber: 13,
      state: "inProgress",
      sourceLessonIds: ["test-completed-lesson"],
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("gamificationEvents/seed-homework-completed").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      eventType: "homework_completed",
      sourceType: "homework",
      sourceId: "test-homework-1",
      xpDelta: 50,
      createdAt: now,
      schemaVersion: 1,
    }),
    db.doc("gamificationEvents/seed-mock-completed").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      eventType: "mock_completed",
      sourceType: "mockExam",
      sourceId: "test-mock-1",
      xpDelta: 100,
      createdAt: now,
      schemaVersion: 1,
    }),
    db.doc("studentAchievements/test-student-program-1__first-step").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      achievementDefinitionId: "first-step",
      earnedAt: now,
      metadata: {},
      schemaVersion: 1,
    }),
    db.doc("studentAchievements/test-student-program-1__battle-baptism").set({
      teacherId: teacherUid,
      studentId: studentUid,
      studentProgramId: "test-student-program-1",
      achievementDefinitionId: "battle-baptism",
      earnedAt: now,
      metadata: {},
      schemaVersion: 1,
    }),
    db.doc("plannerItems/test-planner-today").set({
      teacherId: teacherUid,
      itemType: "task",
      title: "Подготовить материалы к занятию",
      category: "work",
      status: "todo",
      date: localToday,
      startTime: "09:00",
      endTime: null,
      durationMinutes: null,
      deadline: null,
      notes: null,
      priority: "medium",
      goalId: "test-planner-goal",
      subgoalId: "test-planner-subgoal",
      sortOrder: 1,
      completedAt: null,
      active: true,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("plannerItems/test-planner-someday").set({
      teacherId: teacherUid,
      itemType: "task",
      title: "Обновить подборку диктантов",
      category: "someday",
      status: "backlog",
      date: null,
      startTime: null,
      endTime: null,
      durationMinutes: null,
      deadline: null,
      notes: null,
      priority: "calm",
      goalId: null,
      subgoalId: null,
      sortOrder: 2,
      completedAt: null,
      active: true,
      createdAt: now,
      updatedAt: now,
      schemaVersion: 1,
    }),
    db.doc("plannerGoals/test-planner-goal").set({ teacherId: teacherUid, title: "Сильный учебный месяц", description: "Рабочая цель преподавателя", status: "active", targetDate: null, createdAt: now, updatedAt: now, schemaVersion: 1 }),
    db.doc("plannerSubgoals/test-planner-subgoal").set({ teacherId: teacherUid, goalId: "test-planner-goal", title: "Подготовить материалы", notes: "Собрать материалы к ближайшему уроку", status: "active", sortOrder: 1, createdAt: now, updatedAt: now, schemaVersion: 1 }),
  ]);
}
