import { expect, test, type Page } from "@playwright/test";
async function login(page:Page,username:string,password:string,shell:"teacher"|"student"){await page.goto("/#/login");await page.getByLabel("Логин").fill(username);await page.getByLabel("Пароль").fill(password);await page.getByRole("button",{name:"Войти"}).click();await expect(page.getByTestId(`${shell}-shell`)).toBeVisible();}
async function route(page:Page,path:string){await page.evaluate((value)=>{window.location.hash=value;},path);await page.waitForTimeout(100);}
test("teacher can search and preview without impersonation",async({page})=>{await login(page,"test.teacher","Teacher-test-2026!","teacher");await route(page,"/teacher/students");await page.getByLabel("Поиск ученика").fill("Тестовая");await expect(page.getByTestId("student-card")).toHaveCount(1);await page.getByTestId("student-card").click();await page.getByRole("link",{name:"Посмотреть как ученик"}).click();await expect(page.getByText("Режим просмотра преподавателя")).toBeVisible();await expect(page.getByTestId("teacher-shell")).toBeVisible();});
test("teacher provisions a student locally without losing session",async({page})=>{await login(page,"test.teacher","Teacher-test-2026!","teacher");await route(page,"/teacher/students");await page.getByRole("button",{name:"+ Добавить ученика"}).click();const wizard=page.getByRole("dialog");await wizard.getByLabel("Имя").fill("Новая ученица");await wizard.getByLabel("Класс").fill("8");await wizard.getByRole("button",{name:"Далее"}).click();await wizard.getByLabel("Цель").fill("Подтянуть русский язык");await wizard.getByRole("button",{name:"Далее"}).click();await wizard.getByLabel("Логин").fill("phase9b.student");await wizard.getByRole("button",{name:"Далее"}).click();await wizard.getByRole("button",{name:"Создать ученика"}).click();await expect(page.getByRole("heading",{name:"Новая ученица"})).toBeVisible();await expect(page.getByTestId("teacher-shell")).toBeVisible();});
test("calendar exposes month week day timezone and quick lesson",async({page})=>{await login(page,"test.teacher","Teacher-test-2026!","teacher");await route(page,"/teacher/calendar");await expect(page.getByTestId("teacher-month-calendar")).toBeVisible();await page.getByRole("button",{name:"Неделя"}).click();await expect(page.getByTestId("teacher-week-calendar")).toBeVisible();await expect(page.getByText(/Сейчас:/)).toBeVisible();await page.getByRole("button",{name:"Плюс один час"}).click();await expect(page.getByRole("button",{name:"Вернуться к моему времени"})).toBeVisible();await page.getByRole("button",{name:"День"}).click();await expect(page.getByTestId("teacher-day-calendar")).toBeVisible();});
test("homework is presented as a multi-item package",async({page})=>{await login(page,"test.teacher","Teacher-test-2026!","teacher");await route(page,"/teacher/students");await page.getByTestId("student-card").first().click();await page.getByRole("navigation",{name:"Разделы карточки ученика"}).getByRole("link",{name:"Домашние задания",exact:true}).click();const form=page.getByTestId("homework-package-form");await form.getByRole("button",{name:"+ Добавить пункт"}).click();await expect(form.locator(".homework-edit-item")).toHaveCount(2);});
test("global mock history and aggregate analytics are available",async({page})=>{await login(page,"test.teacher","Teacher-test-2026!","teacher");await route(page,"/teacher/mock-exams");await expect(page.getByRole("heading",{name:"Все пробники"})).toBeVisible();await expect(page.locator(".mock-history-card")).toHaveCount(2);await route(page,"/teacher/analytics");await expect(page.getByRole("heading",{name:"Сводка группы"})).toBeVisible();});
test("student has lessons navigation and Russian-facing values",async({page})=>{await login(page,"test.student","Student-test-2026!","student");await expect(page.getByRole("link",{name:/Занятия/})).toBeVisible();await route(page,"/student/homework");await expect(page.locator("body")).not.toContainText(/WRITTEN|PRACTICE|assigned|unpaid/);await route(page,"/student/lessons");await expect(page.getByRole("heading",{name:"Мои занятия",exact:true,level:1})).toBeVisible();});
test("teacher edits an existing mock instead of creating a duplicate",async({page})=>{await login(page,"test.teacher","Teacher-test-2026!","teacher");await route(page,"/teacher/mock-exams");await expect(page.locator(".mock-history-card")).toHaveCount(2);const before=await page.locator(".mock-history-card").count();await page.getByRole("button",{name:"Подробнее"}).first().click();await page.getByRole("button",{name:"Редактировать"}).click();const dialog=page.getByRole("dialog",{name:"Редактировать пробник"});await expect(dialog.locator('input[name="mockTitle"]')).not.toHaveValue("");await expect(dialog.locator('input[name="mockDate"]')).not.toHaveValue("");await dialog.getByRole("button",{name:"Сохранить изменения"}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole("dialog",{name:"Отчёт по пробнику"})).toBeVisible();await expect(page.locator(".mock-history-card")).toHaveCount(before);});
